import { useState } from 'react'
import { unauthPage } from '@/middlewares/authorizationPage'
import Head from 'next/head'
import Link from 'next/link'

export async function getServerSideProps(ctx) {
	await unauthPage(ctx)

	return { props: {} }
}

export default function Register() {
	const [fields, setFields] = useState({
		email: '',
		password: '',
	})

	const [status, setStatus] = useState('normal')

	async function registerHandler(e) {
		e.preventDefault()

		setStatus('loading')

		const registerReq = await fetch('/api/auth/register', {
			method: 'POST',
			body: JSON.stringify(fields), // karena object, harus djadikan json dulu
			headers: {
				'Content-Type': 'application/json',
			},
		})

		if (!registerReq.ok) return setStatus('error ' + registerReq.status)

		const registerRes = await registerReq.json()

		setStatus('success')
	}

	function fieldHandler(e) {
		const name = e.target.getAttribute('name')

		setFields({
			...fields,
			[name]: e.target.value, // name di dalam array agar dinamis
		})
	}

	return (
		<>
			<Head>
				<title>Next Full | Register</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Register</h1>
			<form className='form' onSubmit={registerHandler.bind(this)}>
				<input
					name='email'
					onChange={fieldHandler.bind(this)}
					type='text'
					placeholder='Email'
				/>
				<br />
				<input
					name='password'
					onChange={fieldHandler.bind(this)}
					type='password'
					placeholder='Password'
				/>
				<br />
				<button type='submit'>Register</button>
			</form>
			<div>
				<br />
				<p>Status: {status}</p>
				<br />
				<Link href='/auth/login'>&gt; Login</Link>
			</div>
		</>
	)
}
