import { useState } from 'react'
import { authPage } from '@/middlewares/authorizationPage'
import { useRouter } from 'next/router'
import Nav from '@/components/Nav'
import Head from 'next/head'

export async function getServerSideProps(ctx) {
	const { token } = await authPage(ctx)

	return {
		props: {
			token,
		},
	}
}

export default function PostCreate(props) {
	const [fields, setFields] = useState({
		title: '',
		content: '',
	})

	const [status, setStatus] = useState('normal')

	const router = useRouter()

	async function createHandler(e) {
		e.preventDefault()
		setStatus('loading')

		const { token } = props

		const create = await fetch('/api/posts/create', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				Authorization: 'Bearer ' + token,
			},
			body: JSON.stringify(fields),
		})

		if (!create.ok) return setStatus('error')

		const res = await create.json()

		setStatus('success')

		router.push('/posts')
	}

	function fieldHandler(e) {
		const name = e.target.getAttribute('name')

		setFields({
			...fields,
			[name]: e.target.value,
		})
	}
	return (
		<>
			<Head>
				<title>Next Full | Create Post</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Create Post</h1>
			<br />
			<Nav />
			<br />
			<br />
			<form action='' onSubmit={createHandler.bind(this)}>
				<input
					onChange={fieldHandler.bind(this)}
					type='text'
					placeholder='Title'
					name='title'
				/>
				<br />
				<textarea
					onChange={fieldHandler.bind(this)}
					name='content'
					id=''
					cols='20'
					rows='10'
					placeholder='Content'
				></textarea>
				<br />
				<button type='submit'>Create post</button>
			</form>
			<div>Status: {status}</div>
		</>
	)
}
