import Nav from '@/components/Nav'
import { authPage } from '@/middlewares/authorizationPage'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'

export async function getServerSideProps(ctx) {
	const { token } = await authPage(ctx)

	// fetch aslinya hanya support ambil data di client
	// nextjs mempermudah dg bisa menerapkannya ambil data dari server
	// url fetch haruslah absolut: misal awalnya harus pake http, tidak boleh langsung direktori, bukan relative
	const postReq = await fetch('http://localhost:3000/api/posts', {
		headers: {
			Authorization: 'Bearer ' + token,
		},
	})

	const posts = await postReq.json()

	return {
		props: {
			token,
			posts: posts.data,
		},
	}
}

export default function PostIndex(props) {
	const [posts, setPosts] = useState(props.posts)
	// console.log(posts)

	async function deleteHandler(id, e) {
		e.preventDefault()

		const { token } = props

		const ask = confirm('Yakin ingin menghapus?')

		if (ask) {
			// hapus di database dulu
			const deletePost = await fetch(`/api/posts/delete/${id}`, {
				method: 'DELETE',
				headers: {
					Authorization: 'Bearer ' + token,
				},
			})

			const res = await deletePost.json()

			// kemudian hapus di ui
			const postsFiltered = posts.filter(post => {
				return post.id !== id && post
			})

			setPosts(postsFiltered)
		}
	}

	const router = useRouter()

	function editHandler(id) {
		router.push('/posts/edit/' + id)
	}

	return (
		<>
			<Head>
				<title>Next Full | Posts</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Posts</h1>
			<br />
			<Nav />
			<br />
			<div>
				{posts.map(post => (
					<div key={post.id}>
						<br />
						<h3>{post.title}</h3>
						<p>{post.content}</p>
						<br />
						<p>
							<button onClick={editHandler.bind(this, post.id)}>Edit</button>
							&nbsp;
							<button onClick={deleteHandler.bind(this, post.id)}>
								Delete
							</button>
						</p>
						<br />
						<hr />
					</div>
				))}
			</div>
		</>
	)
}
