import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
	return (
		<>
			<Head>
				<title>Next Full</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1>Home</h1>
				<br />
				<Link href='/auth/login'>Login</Link>
				&nbsp; | &nbsp;
				<Link href='/auth/register'>Register</Link>
			</main>
		</>
	)
}
